### ISSUE TITLE
Pulsate on a button doesn't work on bootstrap

### ISSUE THREAD

**Issue by blackholegalaxy** [Kilian/jQuery.pulsate#13]
Hi Kilian,

Tried to apply your pulsate animation on a 
```html
<button class="btn btn-default" id="pulsate">Pulsate</button>
```

But it doesn't seem to work on this kind of element. On a div, it works.I think BTN bootstrap class removes the outline by setting it at 0 !important.

Here is the JS i use:
```javascript
jQuery('#pulsate').pulsate({
    color: "#bf1"
 });
```

Works if i use a div:
```html
<div id="pulsate">Pulsate</div>
```

Is there any way to get a bypass of btn outline: 0 !important setting?

**Comment by Kilian** [comment]
Hi Blackhole,

It's bootstrap's default settings that's overwriting the outline that jquery.pulsate sets. It works on a button without class btn, so try that and style the button yourself?

Cheers,
Kilian

ps. you did help me find another bug, so thanks!
